version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentiment-analysis-backend
    environment:
      - HF_AUTH_TOKEN=${HF_AUTH_TOKEN}
      - API_KEY=${API_KEY}
    volumes:
      - ./backend/sentiment_history.db:/app/sentiment_history.db
    ports:
      - "8000:8000"
    restart: unless-stopped
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentiment-analysis-frontend
    environment:
      - VITE_API_URL=http://localhost:8000/graphql
      - VITE_API_KEY=${API_KEY}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped